### ISSUE TITLE
Bee Paths Lag Problem

### ISSUE THREAD

**Issue by ImReallyCreative** [mouahrara/aedenthorn#1]
When a bee house has no flower to "connect" to and send bees to, it significantly reduces framerates, especially if there are several in the same area. This only happens as long as those bee houses are on-screen. My guess is that the mod is constantly checking for full-grown flowers and b/c it finds none, it never stops searching; maybe limit how many times each bee house can search for flowers?

**Comment by mouahrara** [comment]
I've updated my unofficial version to improve performance and fix some bugs. Performance should be significantly better when the hives are not connected to crops and slightly better when they are connected to crops.

See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/BeePaths/release-notes.md#021-unofficial2-mouahrara)
