### ISSUE TITLE
Buff Framework Health and Stamina Regens are OP

### ISSUE THREAD

**Issue by Adalghizar** [mouahrara/aedenthorn#3]
Hello, great work on the conversions! I have noticed the regens work TOO well. I think aedenthorn only allowed integers in the original code. Perhaps allowing a float value below 1, like 0.1 to 0.9, will help alleviate that?

Thank you and take care!

**Comment by mouahrara** [comment]
Your suggestion has been implemented in the latest version of the mod (0.6.1-unofficial.5-mouahrara).

See: [Release notes](https://github.com/mouahrara/aedenthorn/blob/master/BuffFramework/release-notes.md#061-unofficial5-mouahrara)
