### ISSUE TITLE
InstantBuildingConstructionAndUpgrade.dll doesn't exist

### ISSUE THREAD

**Issue by gjt186** [mouahrara/aedenthorn#5]
[SMAPI]       - Instant Building Construction and Upgrade 0.2.1-unofficial.1-mouahrara because its DLL 'InstantBuildingConstructionAndUpgrade.dll' doesn't exist.

Thank you for your efforts! When I used this mod,smapi reported an error, I noticed that there was no dll file with the same name in the folder, can you handle it? Thank you!

**Comment by mouahrara** [comment]
The **InstantBuildingConstructionAndUpgrade.dll** file should be included in the downloaded zip. It’s possible that your antivirus is detecting it as a dangerous file (false positive) and deleting it. (See: [SMAPI or mod files disappear](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#SMAPI_or_mod_files_disappear,_or_they're_blocked_by_your_antivirus_or_browser))

**Comment by gjt186** [comment]
I put the decompressed folder directly into SteamLibrary\steamapps\common\Stardew Valley\Mods like any other mod
Besides, all firewalls were closed, and smapi still reported errors. In addition, I saw no dll file in the folder on github

**Comment by mouahrara** [comment]
The GitHub repository contains the source files for each mod (.cs), which are compiled into a single .dll file. Therefore, it is normal for the GitHub repository not to contain the .dll files for the mods; they should only be included in the downloadable zip files. These zip files are the compiled versions of each mod and should contain the **manifest.json** file, the **[ModName].dll** file, and optionally an **i18n** folder and an **assets** folder.

Regarding the missing **InstantBuildingConstructionAndUpgrade.dll** file, did you download the zip file using the direct download link in the Readme? Here are the detailed instructions for downloading and installing my unofficial version of the Instant Building Construction and Upgrade mod:
1. Download the [InstantBuildingConstructionAndUpgrade-0.2.1-unofficial.1-mouahrara.zip](https://github.com/mouahrara/aedenthorn/releases/download/main-files/InstantBuildingConstructionAndUpgrade-0.2.1-unofficial.1-mouahrara.zip) file.
2. Unzip the file and check its contents. You should have the following structure:
```
📁 InstantBuildingConstructionAndUpgrade/
	🗎 manifest.json
	🗎 InstantBuildingConstructionAndUpgrade.dll
	📁 i18n/
		🗎 default.json
		🗎 fr.json
```
3. Move the **InstantBuildingConstructionAndUpgrade** folder to the `C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods` folder.

If the **InstantBuildingConstructionAndUpgrade** folder does not contain the **InstantBuildingConstructionAndUpgrade.dll** file, it may have been quarantined or deleted by your antivirus software.
